---
title: "Spawn night protocol"
subtitle: "For embryonic development of Montipora capitata rice corals"
author: "Sarah Tanja"
date: '03/26/2024'
---

# Prep

\*\*Filtering leachate & dilution took about 45 minutes\*\*

## Make Stock Leachate

First make 400mL of each stock solution from the 1000 mg/L prepared leachate

-   [ ] Make 10 mg/L stock:

    1000 mg/L \* V1 = 10 mg/L \* 400mL

    V1 = 4mL

    400mL of 10mg/L stock = 4mL of 1000mg/L stock + 396mL of FSW

-   [ ] Make 1mg/L stock:

    10mg/L \* V1 = 1mg/L \* 400mL

    V1 = 40mL

    400mL of 1mg/L stock = 40mL of 10mg/L stock + 360mL of FSW

-   [ ] Make 0.1 mg/L stock:

    1mg/L \* V1 = 0.1mg/L \* 400mL

    V1 = 40mL

    400mL of 0.1mg/L stock = 40mL of 1mg/L stock + 360mL of FSW

2.  Then dilute the stock to each treatment vial/jar

For a 20mL scintillation vial for coral embryo experiments with a final target volume of 15mL:

**1mg/L HIGH treatment**

10mg/L \* V1 = 1mg/L \* 19mL

V1 = 1.9mL

19mL of 1mg/L leachate = 17.1mL of FSW + 1.9mL of 10mg/L stock

**0.1 mg/L MID treatment**

1mg/L \* V1 = 0.1mg/L \* 20mL

V1 = 12mL

20mL of 0.1mg/L leachate = 18mL of FSW + 2mL of 1mg/L stock

**0.01 mg/L LOW treatment**

0.1mg/L \* V1 = 0.01mg/L \* 18mL

V1 = 2mL

20mL of 0.01mg/L leachate = 18mL of FSW + 2mL of 0.1mg/L stock

## ZFIX

Going from 18.5% to 4% in a \~100mL final volume!

We want a total of 100 mL volume

0.185 \* V1 = 0.04 \* 100mL

V1 = 21.62mL

To get 100mL of 4% ZFIX: Add 21.62 mL of 18.5% ZFIX to 78.38mL of (0.22micron) filtered sea water

::: callout-important
Jill Ashey says it's important to use FSW to dilute your ZFIX! This is for long-term storage (up to 6 months) of embryos in anywhere from 4-20% ZFIX or paraformaldehyde (PFA) ... the FSW may keep your embryos from lysing so that you can preserve their entegrity for microscopy.
:::

## Freeze (& shield)

To preserve embryos for RNA extraction and sequencing we will first submerge them in Zymo DNA/RNA Shield, and then pronptly transfer them to a -80C freezer. Here, we won't be dunking them in LN2. The combined DNA/RNA Shield and the quick freeze (due to small size) they will experience in the -80 are together sufficient for preserving RNA.

We will first very gently use a tip-clipped transfer pipette to transfer embryos to our 0.5mL screw-cap cryo-tubes. Wewill then carefully decant any excess FSW out of the tube, and then add 500uL of Zymo RNA/DNA Shield. Gently invert cryo-tubes a few times to ensure embryos are fully submerged. Once cryo-tubes are filled with their samples, arrange them in wax paper boxes and promptly shift them to -80°C freezer for storage until samples are ready to be processed.

# Spawn Night

### 19:00 - 19:30

-   [ ] Move each colony to a numbered/named cambro chamber bin or 5 gallon bucket
-   [ ] Ensure each colony has enough headspace so that bundles can rise to the surface
-   [ ] Reduce blue holding tank water level to below the lip of the chambers
-   [ ] Decant water in chambers such that bouyant bundles don't spill out

### 19:30 - 20:00

-   [ ] Organize the following collection materials at the spawning tubs:

    -   [ ] 50mL falcon tubes (1 for ea. colony) filled with 30mL of 0.22micron FSW
    -   [ ] Tip-clipped transfer pipettes
    -   [ ] Red Headlamps (new batteries)
    -   [ ] Printed waterproof spawn collection data sheet

-   [ ] Organize the following collection materials at the dry lab bench:

    -   [ ] 20mL scintillation vials prepped with treatments

    -   [ ] 50mL falcon tube rack (for working with active bundle-bundle crosses)

    -   [ ] Tip-clipped transfer pipettes (for moving bundles to scintillation vials)

    -   [ ] Printed waterproof bundle-bundle cross metadata sheet (for recording parent colonies of crosses)

### 20:50 - 21:20

-   [ ] Observe for setting (polyp expansion and bundle visibility) via red headlamp
-   [ ] Find a spawner!
-   [ ] Collect 24 bundles from each spawning colony and transfer them to a pre-labeled 50mL falcon tube with 30mL of FSW
-   [ ] Once we have at least 2 colonies worth of bundles, 1 person will move with any filled falcon tubes to the dry lab bench and begin bundle-bundle crosses
-   [ ] 1 person will remain and continue to collect bundles from colonies, periodically transferring them to the bundle-bundle crossing station at the dry lab bench

### 21:20 - 22:00

-   [x] Cross fertilize by taking one bundle each from two distinct colonies and transferring them to the same scintillation vial
-   [x] Record the parent colonies of each cross on the embryonic development metadata sheet
-   [x] Only transfer intact bundles! Once eggs break up and begin to hydrate, the spawn party is over

### 22:00 - 22:30

-   [x] Observe scintillation vials for bundle breakup and egg hydration

-   [ ] Record the times when the first and last vials experience hydration

    -   [x] First Egg Hydration Time\_\_\_\_\_22:00\_\_\_\_\_\_\_\_

    -   [ ] Last Egg Hydration Time\_\_\_\_\_22:\_\_\_\_\_\_\_\_\_\_

-   [ ] Average the times above , and add 4 hours, 9 hours, and 14 hours

    -   [ ] Average Egg Hydration Time\_\_\_22:20\_\_\_\_

    -   [ ] 4 hours post-fertilization[^1]\_\_\_\_\_02:20\_\_\_\_\_

    -   [ ] 9 hours post-fertilization\_\_\_\_\_\_07:20\_\_\_\_\_

    -   [ ] 14 hours post fertilization\_\_\_\_\_\_12:20\_\_\_

-   Set alarms for \~40 minutes prior to the times above

[^1]:
    -   [ ] (& on July 6th make another batch of leachate!)

### 22:30 - 23:00

-   [ ] Return each colony to blue tank and remove chambers

-   [ ] Return water height to normal

-   [ ] Clean up anything left outside

### 23:00 - 01:45

-   [ ] 2.5 hr nap time!

### 02:15 - 03:30

-   [ ] ZFIX 4hpf samples (4Z)

    -   [ ] Use a transfer pipette to gently move embryos from scintillation vials to microcentrifuge tubes
    -   [ ] Decant any excess FSW with transfer pipette
    -   [ ] Add \~1mL of 4% ZFIX to each microcentrifuge tube in the fume hood!
    -   [ ] Gently invert each capped scintillation vial to mix the ZFIX into the filtered seawater and sample
    -   [ ] Record time of fixin' : \_\_\_\_\_\_\_\_\_\_
    -   [ ] Add 8-12 hours to fixin' time to transfer from ZFIX to 70% ethanol: \_\_\_\_\_\_\_\_\_\_\_\_
    -   [ ] Set fixed vials in 4C fridge

-   [ ] Freeze 4hpf samples (4F)

    -   [ ] Gently transfer live embryos to cryo-vials

    -   [ ] Decant excess FSW using a transfer pipette

    -   [ ] Add 500uL of Zymo DNA/RNA Shield

    -   [ ] Promptly transfer to -80C freezer

-   [ ] Make PVC Leachate (on July 6th!)

### 03:30 - 06:45

-   [ ] 3.25 hr nap time!

### 07:15 - 08:30

-   [ ] ZFIX 9hpf samples (9Z)

    -   [ ] Use a transfer pipette to gently move embryos from scintillation vials to microcentrifuge tubes
    -   [ ] Decant any excess FSW with transfer pipette
    -   [ ] Add \~1mL of 4% ZFIX to each microcentrifuge tube in the fume hood!
    -   [ ] Gently invert each capped scintillation vial to mix the ZFIX into the filtered seawater and sample
    -   [ ] Record time of fixin' : \_\_\_\_\_\_\_\_\_\_
    -   [ ] Add 8-12 hours to fixin' time to transfer from ZFIX to 70% ethanol: \_\_\_\_\_\_\_\_\_\_\_\_
    -   [ ] Set fixed vials in 4C fridge

-   [ ] Freeze 9hpf samples (9F)

    -   [ ] Gently transfer live embryos to cryo-vials

    -   [ ] Decant excess FSW using a transfer pipette

    -   [ ] Add 500uL of Zymo DNA/RNA Shield

    -   [ ] Promptly transfer to -80C freezer

### 08:30 - 11:45

-   [ ] 3.25 hr nap time!

### 12:15 - 13:30

-   [ ] ZFIX 14hpf samples (14Z)

    -   [ ] Use a transfer pipette to gently move embryos from scintillation vials to microcentrifuge tubes
    -   [ ] Decant any excess FSW with transfer pipette
    -   [ ] Add \~1mL of 4% ZFIX to each microcentrifuge tube in the fume hood!
    -   [ ] Gently invert each capped scintillation vial to mix the ZFIX into the filtered seawater and sample
    -   [ ] Set fixed vials in 4C fridge

-   [ ] Freeze 14hpf samples (14F)

    -   [ ] Gently transfer live embryos to cryo-vials

    -   [ ] Decant excess FSW using a transfer pipette

    -   [ ] Add 500uL of Zymo DNA/RNA Shield

    -   [ ] Promptly transfer to -80C freezer

::: callout-tip
You can do this!
:::
